version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: latest
    rust: latest

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
